apiVersion: apps/v1
kind: Deployment
metadata:
  name: psms-web
  labels:
    app: psms-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psms-web
  template:
    metadata:
      labels:
        app: psms-web
    spec:
      containers:
      - name: psms-web
        image: nginx:latest
        ports:
        - containerPort: 80
